[package]
name = "dorst"
version = "0.4.2"
edition = "2021"
repository = "https://github.com/charlesrocket/dorst"
authors = ["charlesrocket"]
description = "Codebase backup utility"
categories = ["command-line-utilities"]
keywords = ["backup", "git"]
license = "MIT"
readme = "README.md"
exclude = [".github"]

[profile.release]
debug = 0
strip = true
lto = true

[dependencies]
anyhow = "1.0"
clap = { version = "4.1", features = ["string"] }
git2 = "0.16"
indicatif = "0.17"
rpassword = "7.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
shellexpand = "3.0"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
tempfile = "3"
