name: CD
on:
  workflow_call:
    secrets:
      CRATES_TOKEN:
        required: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    name: Create release
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    needs: create-release
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
